apps/contentAdmin/urls.py
from django.urls import path
from . import views

app_name='contentAdmin'

urlpatterns = [
    path('', views.upload_index, name='upload_index'),
    path('upload/', views.upload_index, name='upload_index'),
    path('upload-csv/', views.upload_csv_api, name='upload_csv_api'),
    path('upload/upload-csv/', views.upload_csv_api, name='upload_csv_api'),
    path('download/', views.download_index, name='download_index'),
    path('download/create/', views.create_csv_file, name='create_csv_file'),
    path('download/file/<str:file_name>/', views.download_csv_file, name='download_csv_file')

]

apps/main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.contrib.auth.decorators import login_required

app_name='main'

urlpatterns = [
    path('', views.main_index, name='selectDB'),
    path('login/', views.login_index, name='login'),
    path('userLogin/', views.user_login, name='userLogin'),
    path('selectDB/', views.main_index, name='selectDB'),
    path('logout/', views.user_logout, name='userLogout')
]

config/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('contentAdmin/', include('apps.contentAdmin.urls')),
    path('', include('apps.main.urls')),
]

apps/contentAdmin/models.py
from django.db import models

# Create your models here.

apps/main/models.py
from django.db import models

# Create your models here.

apps/contentAdmin/views.py
from django.shortcuts import render
import csv, json
import io
from django.http import JsonResponse, HttpResponseBadRequest, Http404,FileResponse
from django.conf import settings
import pandas as pd
from base.MongoClass.MongoContent import MongoContent
import asyncio, os
from datetime import datetime
from urllib.parse import unquote
from django.contrib.auth.decorators import login_required

CSV_DIR = os.path.join(settings.MEDIA_PATH, 'tmp')

@login_required(login_url='main:login')
def upload_index(request):
    #업로드 html 폼 렌더링
    return render(request, 'contentAdmin/upload.html')

def get_mongo_db_collection(collection_name):
    mc = MongoContent(collection_name)
    mc.login(userid=settings.DB_ID, pw=settings.DB_PASSWORD, dbip=settings.DB_IP)
    return mc

@login_required(login_url='main:login')
def upload_csv_api(request):
    """
    비동기 POST 요청을 받아 CSV 파일을 처리하고 MongoDB에 저장하는 API 엔드포인트.
    """
    if request.method != 'POST':
        # POST 요청만 허용
        return JsonResponse({'status': 'error', 'message': 'Invalid request method.'}, status=405)

    # 컬렉션 이름과 파일 확인
    collection_name = request.POST.get('collection_name')
    if not collection_name:
        return JsonResponse({'status': 'error', 'message': '컬렉션 이름이 지정되지 않았습니다.'}, status=400)

    if 'csv_file' not in request.FILES:
        # 파일 선택 여부 확인
        return JsonResponse({'status': 'error', 'message': '업로드된 파일이 없습니다.'}, status=400)
    csv_file = request.FILES['csv_file']

    # 데이터 타입 확인
    data = []
    try:
        if not csv_file.name.endswith('.csv'):
            return JsonResponse({'status': 'error', 'message': 'CSV 파일만 지원됩니다.'}, status=400)
        #파일 dict 타입으로 변환
        file_data = csv_file.read().decode('utf-8')
        csv_data = io.StringIO(file_data)
        reader = csv.DictReader(csv_data)

        for row in reader:
            data.append(row)

    except Exception as e:
        return JsonResponse({'status': 'error', 'message': f'파일 처리 중 오류 발생: {e}'}, status=500)

    # 데이터 정합성 확인 및 MongoDB 업로드
    try:
        client = get_mongo_db_collection(collection_name)
        asyncio.run(client.insert(data))

        # 성공 응답 (JSON)
        return JsonResponse({
            'status': 'success',
            'message': f'총 {len(data)}개의 레코드가 "{collection_name}" 컬렉션에 성공적으로 업로드되었습니다.'
        }, status=200)

    except Exception as e:
        # DB 연결 또는 삽입 오류
        return JsonResponse({'status': 'error', 'message': f'MongoDB 업로드 중 오류 발생: {e}'}, status=500)

@login_required(login_url='main:login')
def download_index(request):
    return render(request, 'contentAdmin/download.html')

#POST 요청을 받아 DB 쿼리를 실행하고 CSV 파일 생성
@login_required(login_url='main:login')
def create_csv_file(request):
    if request.method != 'POST':
        # POST 요청만 허용
        return JsonResponse({'status': 'error', 'message': 'Invalid request method.'}, status=405)
    # 컬렉션 이름 및 쿼리 확인
    query = request.POST.get('query')
    if not query:
        return JsonResponse({'status': 'error', 'message': '쿼리를 입력해주세요.'}, status=400)
    collection_name = request.POST.get('collection_name')
    if not collection_name:
        return JsonResponse({'status': 'error', 'message': '컬렉션 이름이 지정되지 않았습니다.'}, status=400)

    # 쿼리 실행 및 결과 가져오기
    try:
        client = get_mongo_db_collection(collection_name)
        query_filter = json.loads(unquote(query))  # 텍스트 형식 쿼리 필터 dictionary 형으로 변환
    except Exception as e:
        return JsonResponse({'status':'error', 'message':f'쿼리 변환 중 오류가 발생했습니다.: {e} {query}'}, status=500)
    try:
        data = asyncio.run(client.find(query_filter=query_filter, n=-1))
        result = pd.DataFrame(data)
    except Exception as e:
        # 쿼리 실행 중 오류 발생 시
        return JsonResponse({'status': 'error', 'message': f'DB 쿼리 실행 중 오류가 발생했습니다: {e}'}, status=500)

    # CSV 파일 생성
    try:
        # 디렉토리가 없으면 생성
        os.makedirs(CSV_DIR, exist_ok=True)
        # 파일 이름 설정
        now = datetime.now().strftime('%Y%m%d%H%M%S')
        file_name = f'query_result{now}.csv'
        file_path = os.path.join(CSV_DIR, file_name)
        #파일 저장
        result.to_csv(file_path, encoding='utf-8', index=False)

        # 성공 응답
        return JsonResponse({
            'status': 'success',
            'message': f'CSV 파일이 서버에 생성되었습니다: {file_name}',
            'file_name': file_name  # 다운로드 뷰에 전달할 파일 이름
        })

    except Exception as e:
        # 파일 생성 중 오류 발생 시
        return JsonResponse({'status': 'error', 'message': f'CSV 파일 생성 중 오류가 발생했습니다: {e}'}, status=500)


#GET 요청을 받아 서버에 있는 CSV 파일을 다운로드
@login_required(login_url='main:login')
def download_csv_file(request, file_name):
    file_path = os.path.join(CSV_DIR, file_name)
    #  파일 존재 여부 확인
    if not os.path.exists(file_path):
        raise Http404("파일을 찾을 수 없습니다.")

    # FileResponse를 사용하여 파일 다운로드
    try:
        response = FileResponse(open(file_path, 'rb'), content_type='text/csv')
        # Content-Disposition 헤더 설정: 'attachment'로 설정해야 다운로드됨
        response['Content-Disposition'] = f'attachment; filename="{file_name}"'
        return response
    except Exception as e:
        raise Http404(f"파일 다운로드 중 오류 발생: {e}")

apps/main/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
@login_required(login_url='main:login')
def main_index(request):
    return render(request, 'main/select_db.html')

def login_index(request):
    return render(request, 'main/login.html')

def user_login(request):
    if request.method == 'POST':
        # 1. 사용자 인증 (Credentials 검증)
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])

        if user is not None:
            # 2. 세션 설정 (사용자를 '로그인' 상태로 만듦)
            # 이 함수가 auth_user_id를 세션에 저장하여 '로그인 상태'를 유지합니다.
            login(request, user)
            request.session['username'] = request.POST['username']

            return redirect('main:selectDB')  # 'home'은 login_required가 적용된 페이지여야 합니다.
        else:
            # 인증 실패 처리
            return render(request, 'main/login.html', {'error': 'Invalid credentials'})

def user_logout(request):
    logout(request)
    return redirect('main:login')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="KO-kr">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>{% block title %}DB 관리 페이지{% endblock title %}</title>
</head>
<body>
<!--네비게이션 바-->
{% include "navbar.html" %}
<!--두번째 줄 네비게이션 바 추가-->
{% block nav %}
{% endblock nav %}

<div class="container mt-3">
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock content %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
</div>
</body>
</html>

templates/contentAdmin/download.html
{% extends 'base.html' %}
{% block title %}
콘텐츠 DB 관리
{% endblock title %}

{% block nav %}
{% include "contentAdminNavbar.html" %}
{% endblock nav %}

{% block content %}

<form class="row g-3" method="post" enctype="multipart/form-data" action="{% url 'contentAdmin:download_index' %}" id="upload_form_data">
    {% csrf_token %}

    <div style="margin-bottom: 20px;" class="form-check">
        <p>다운로드할 콜렉션을 선택하세요</p>

        <input class="form-check-input" type="radio" id="CONTENT" name="collection_name" value="CONTENT" required>
        <label class="form-check-label" for="CONTENT">CONTENT</label><br>

        <input class="form-check-input" type="radio" id="UNIQUE_CONTENT" name="collection_name" value="UNIQUE_CONTENT">
        <label class="form-check-label" for="UNIQUE_CONTENT">UNIQUE_CONTENT</label><br>

        <input class="form-check-input" type="radio" id="SUMMARY_INFO" name="collection_name" value="SUMMARY_INFO">
        <label class="form-check-label" for="SUMMARY_INFO">SUMMARY_INFO</label><br>

        <input class="form-check-input" type="radio" id="WEBSITE_DOMAIN" name="collection_name" value="WEBSITE_DOMAIN">
        <label class="form-check-label" for="WEBSITE_DOMAIN">WEBSITE_DOMAIN</label><br>
    </div>
    <div>
        <p>쿼리 조건을 입력하세요.</p>
        <div style="width:50%">
            <div class="input-group">
              <span class="input-group-text">Query</span>
              <textarea id="mongo_query" class="form-control" aria-label="With textarea" placeholder="여기에 몽고DB 쿼리를 입력하세요."></textarea>
            </div>
        </div>
         <!--<textarea id="mongo_query" rows="10" cols="80" placeholder="여기에 몽고DB 쿼리를 입력하세요."></textarea>-->
    <br>
        <button class="btn btn-primary" id="create_file_button">파일 생성</button>
    </div>
    <div>

        <button class="btn btn-primary" type="button" id="download_file_button" disabled>다운로드</button>
        <input type="hidden" id="download_url" value="">

    </div>

    <div id="message_area" style="margin-top: 20px;"></div>

</form>

{% load static %}
<script src="{% static 'contentAdmin/download.js' %}"></script>

{% endblock content %}

templates/contentAdmin/upload.html
{% extends 'base.html' %}
{% block title %}
콘텐츠 DB 관리
{% endblock title %}

{% block nav %}
{% include "contentAdminNavbar.html" %}
{% endblock nav %}

{% block content %}
<form class="row g-3" method="post" enctype="multipart/form-data" action="{% url 'contentAdmin:upload_index' %}" id="upload_form_data">
    {% csrf_token %}

    <div style="margin-bottom: 20px;" class="form-check">
        <p>업로드할 콜렉션을 선택하세요</p>

        <input class="form-check-input" type="radio" id="CONTENT" name="collection_name" required>
        <label class="form-check-label" for="CONTENT">CONTENT</label><br>

        <input class="form-check-input" type="radio" id="UNIQUE_CONTENT" name="collection_name">
        <label class="form-check-label" for="UNIQUE_CONTENT">UNIQUE_CONTENT</label><br>

        <input class="form-check-input" type="radio" id="SUMMARY_INFO" name="collection_name">
        <label class="form-check-label" for="SUMMARY_INFO">SUMMARY_INFO</label><br>

        <input class="form-check-input" type="radio" id="WEBSITE_DOMAIN" name="collection_name">
        <label class="form-check-label" for="WEBSITE_DOMAIN">WEBSITE_DOMAIN</label><br>

        </div>

    <div class="container-sm">
        <div>
            <p>업로드할 CSV 파일을 선택해주세요.</p>
        </div>
        <div class="input-group" style="width:50%">
            <input type="file" class="form-control" id="csv_file" name="csv_file" accept=".csv" aria-label="Upload">
            <button class="btn btn-outline-secondary" type="submit" value="업로드" id="upload_button" disabled >업로드</button>
        </div>
    </div>
    <!--<div>
        <label for="csv_file">업로드할 CSV 파일을 선택해주세요.</label>
        <input type="file" id="csv_file" name="csv_file" accept=".csv">
    </div>
    <input type="submit" value="업로드" id="upload_button" disabled style="margin-top: 15px;">
    -->
</form>

<div id="message_area" style="margin-top: 20px;"></div>
{% load static %}
<script src="{% static 'contentAdmin/upload.js' %}"></script>

{% endblock content %}

templates/contentAdminNavbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
<div class="container-fluid">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item"><a class="nav-link" href="{% url 'contentAdmin:upload_index' %}">업로드</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'contentAdmin:download_index' %}">다운로드</a></li>
        </ul>
    </div>
</nav>

templates/main/login.html
<!DOCTYPE html>
<html lang="KO-kr">
<head>
    <meta charset="UTF-8">
    <title>로그인 페이지</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

</head>
<body>
<div class="d-flex justify-content-center">
<div class="login-box border rounded">
    <form method="post" action="{% url 'main:userLogin' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
</div>
<div id="message_area" style="margin-top: 20px;"></div>
</body>
{% load static %}
<script src="{% static 'main/login.js' %}"></script>
</html>

templates/main/select_db.html
<!DOCTYPE html>
<html lang="KO-kr">
<head>
    <meta charset="UTF-8">
    <title>DB 선택</title>
    <style>
        /* CSS로 전체 화면 중앙 정렬 및 버튼 스타일 지정 */
        body {
            margin: 0;
            height: 100vh; /* 뷰포트 전체 높이 */
            display: flex;
            justify-content: center; /* 수평 중앙 정렬 */
            align-items: center;     /* 수직 중앙 정렬 */
            flex-direction: column;  /* 버튼을 한 줄로 배치하기 위해 사용 */
            background-color: #f0f0f0;
        }

        .button-container {
            display: flex; /* 버튼을 나란히 배치 */
            gap: 50px;     /* 버튼 사이 간격 */
        }

        .main-button {
            /* 버튼 스타일 */
            padding: 30px 50px;
            font-size: 24px;
            text-decoration: none; /* 앵커 태그 밑줄 제거 */
            color: #5c5c5e;
            border-radius: 10px;
            transition: background-color 0.3s;
        }

        #button-a {
            background-color: #b2cef7; /* 파란색 */
        }

        #button-b {
            background-color: #f7d2b2; /* 주황색 */
        }

        .main-button:hover {
            opacity: 0.8;
        }
    </style>
</head>
<body>
 <div class="button-container">
        <a href="{% url 'contentAdmin:upload_index' %}" id="button-a" class="main-button">
            콘텐츠 DB 관리
        </a>

        <a href="{% url 'contentAdmin:upload_index' %}" id="button-b" class="main-button">
            코퍼스 DB 관리
        </a>
 </div>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark border-bottom">
    <div class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="navbar-brand fw-semibold" href="{% url 'main:selectDB' %}">DB 관리 페이지</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:userLogout' %}">로그아웃</a>
            </li>
            {% endif %}
        </ul>
    </div>

</nav>